config/routes.rb
Rails.application.routes.draw do

  get 'incoming/Controller'

get 'signup', to: 'users#new', as: 'signup'
get 'login', to: 'sessions#new', as: 'login'
get 'logout', to: 'sessions#destroy', as: 'logout'
get 'home', to: 'welcome#index', as: 'home'

resources :users
resources :sessions

resources :topics do
  resources :bookmarks
end

post :incoming, to: 'incoming#create'

root to: 'welcome#index'

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base
  belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :bookmarks
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_uniqueness_of :email
  validates_presence_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_path, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  
  # def index
  #   @bookmark = Bookmark.new
  # end

  # if params[:title]
  #     @bookmark_groups = current_user.bookmarks.where(title: params[:title]).group_by { |b| b.title }
  #   else
  #     @bookmark_groups = current_user.bookmarks.group_by { |b| b.title }
  #   end

  #   if params[:title]
  #     @liked_bookmark_groups = current_user.liked_bookmarks.where(title: params[:title]).group_by { |b| b.title }
  #   else
  #     @liked_bookmark_groups = current_user.liked_bookmarks.group_by { |b| b.title }
  #   end

  # def destroy
  #   @bookmark = Bookmark.find(params[:id])
  #   url = @bookmark.url
  #   authorize @bookmark

  #   if @bookmark.destroy
  #     flash[:notice] = "\"#{url}\" was deleted successfully."
  #     redirect_to bookmarks_path
  #   else
  #     flash[:error] = "There was an error deleting the bookmark."
  #     render "bookmarks/index"
  #   end
  # end

end

app/controllers/incoming_controller.rb
class IncomingController < ApplicationController
# http://stackoverflow.com/questions/1177863/how-do-i-ignore-the-authenticity-token-for-specific-actions-in-rails
  skip_before_filter :verify_authenticity_token, only: [:create]

  def create

    sender_email = params['sender']
    subject_text = params['subject']
    email_body = params["body-plain"]

    # using the sender to find the user
    user = User.find_by_email(sender_email)

    # use the subject to find the topic
    topic = Topic.find_by_title(subject_text)

    # if user is nil, create and save user
    if user.nil?
      user = User.new(email: sender_email, password: "helloworld")
      user.save
    end

    # if topic is nil, create and save topic
    if topic.nil?
      topic = Topic.new(title: subject_text)
      topic.save
    end

    # use the body-plain to create the bookmark
    # assign bookmark to topic and user and save
    bookmark = Bookmark.where(url: email_body, user: user, topic: topic).first  

    if bookmark.nil?
      bookmark = Bookmark.new(url: email_body, user: user, topic: topic)
      bookmark.save
    end


    # Assuming all went well. 
    head 200
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
def new
end

  def create
    user = User.find_by_email(params[:email])
    begin
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to topics_path, notice: "Logged in!"
      else
        flash.now.alert = "Email or password is invalid"
        render "new"
      end
    rescue BCrypt::Errors::InvalidHash
        flash.now.alert = "Your user in invalid, so sorry"
        render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to home_path, notice: "Logged out!"
  end

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def new
  end

  def edit
  end

  def show
    @topic = Topic.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save!
      session[:user_id] = @user.id
      UserMailer.welcome_email(@user).deliver
      redirect_to bookmarks_path, notice: "Thank you for signing up"
    else
      render "new"
    end
  end

private
  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/incoming_helper.rb
module IncomingHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/bookmarks/edit.html.erb
<h1>Bookmarks#edit</h1>
<p>Find me in app/views/bookmarks/edit.html.erb</p>

app/views/bookmarks/index.html.erb
<h1>User Bookmarks</h1>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <h2><a href="http://boards.dawgrun.com/message_board/georgia/">Dawg Run</h2> 
    </div>
  </div>
</div>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <h2><a href="http://www.gamespot.com/articles/monster-hunting-game-evolve-gets-some-cool-3d-prin/1100-6421002/">Evolve</h2> 
    </div>
  </div>
</div>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <h2><a href="http://singularityhub.com/2014/06/25/robotic-hand-uses-ai-to-specialize-its-grip-for-any-object/">Robot hand</h2> 
    </div>
  </div>
</div>

<div class="ui grid">
  <div class="four wide column">
    <div class="ui segment">
      <h2><a href="https://news.ycombinator.com/">Hacker News</h2> 
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<h1>Bookmarks#new</h1>
<p>Find me in app/views/bookmarks/new.html.erb</p>

app/views/bookmarks/show.html.erb
<h1>Bookmarks#show</h1>
<p>Find me in app/views/bookmarks/show.html.erb</p>

app/views/incoming/Controller.html.erb
<h1>Incoming#Controller</h1>
<p>Find me in app/views/incoming/Controller.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flurboo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <ul class="cred_btns">
    <%= link_to home_path, class: "ui icon button" do %>
      <i class="small circular home icon"></i>
      <% end %>
    <%= link_to topics_path, class: "ui icon button" do %>
      <i class="small circular bookmark icon"></i>
      <% end %>
  <% if current_user %>
    <%= link_to topics_path, class: "ui icon button" do %>
      <i class="small circular user icon"></i>
      <% end %>
    <%= link_to logout_path, class: "ui icon button" do %>
      <i class="small circular remove icon"></i>
      <% end %>
  <% else %>
    <%= link_to login_path, class: "ui icon button" do %>
      <i class="small circular sign in icon"></i>
      <% end %>
    <%= link_to signup_path, class: "ui icon button" do %>
      <i class="small circular up icon"></i>
    <% end %>
  <% end %>
  </ul>
    
<%= yield %>

</body>
</html>

app/views/topics/edit.html.erb
<h1>Topics#edit</h1>
<p>Find me in app/views/topics/edit.html.erb</p>

app/views/topics/index.html.erb
<h1>Bookmark Topics</h1>
<% @topics.each do |topic| %>
  <div class="ui grid">
    <div class="four wide column">
      <div class="ui segment">
        <h2><%=link_to topic.title, topic %></h2> 
      </div>
    </div>
  </div>
<% end %>

app/views/topics/new.html.erb
<h1>Topics#new</h1>
<p>Find me in app/views/topics/new.html.erb</p>

app/views/topics/show.html.erb
<h1><%= @topic.title %></h1>

<% @topic.bookmarks.each do |bookmark| %>
  <%= link_to bookmark.url, bookmark.url %>
<% end %>

app/views/users/new.html.erb
<div class="signup">

<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit "Sign Up", class: 'ui green submit button' %></div>
<% end %>
</div>

</div>

app/views/welcome/index.html.erb
<% if current_user %>
<div class="welcome">
  <div class="massive ui circular basic animated fade button">
    <div class="visible content">Welcome!</div>
    <div class="hidden content"><%= link_to "to flurBoo!", topics_path %></div>
  </div>
</div>
<% else %>
  <div class="welcome">
  <div class="massive ui circular basic animated fade button">
    <div class="visible content">Welcome!</div>
    <div class="hidden content"><%= link_to "to flurBoo!", login_path %></div>
  </div>
</div>
<% end %>